// Code generated by core. DO NOT EDIT (base registry, regenerated each run).
using System.IO;

namespace Table
{
	public class BaseTables
	{
		public BaseDemoTable Demo = new BaseDemoTable();

		// LoadAll 从 dir 加载全部 base 表（dir/<name>.tsv）。
		public void LoadAll(string dir)
		{
			Demo.Load(Path.Combine(dir, "Demo.tsv"));
		}
	}
}
