// Code generated by core. DO NOT EDIT (base runtime, regenerated each run).
using System;
using System.Collections.Generic;

namespace Table
{
    // Vector3 三维向量（策划用 ';' 或 ',' 分隔的三个浮点数）。
    public struct Vector3
    {
        public float X, Y, Z;
    }

    public static class TableParsers
    {
        public static string Cell(string[] rec, int i)
        {
            if (i < 0 || i >= rec.Length) return "";
            return rec[i];
        }

        public static int ToInt(string s)
        {
            if (string.IsNullOrWhiteSpace(s)) return 0;
            return int.TryParse(s.Trim(), out var v) ? v : 0;
        }

        public static long ToLong(string s)
        {
            if (string.IsNullOrWhiteSpace(s)) return 0L;
            return long.TryParse(s.Trim(), out var v) ? v : 0L;
        }

        public static float ToFloat(string s)
        {
            if (string.IsNullOrWhiteSpace(s)) return 0f;
            return float.TryParse(s.Trim(), out var v) ? v : 0f;
        }

        public static Dictionary<int, int> ParseMapIntInt(string s)
        {
            var res = new Dictionary<int, int>();
            if (string.IsNullOrWhiteSpace(s)) return res;
            foreach (var pair in s.Split('|'))
            {
                var p = pair.Trim();
                if (p == "") continue;
                var kv = p.Split(new[] { ';' }, 2);
                if (kv.Length != 2) kv = p.Split(new[] { ':' }, 2);
                if (kv.Length != 2) continue;
                res[ToInt(kv[0])] = ToInt(kv[1]);
            }
            return res;
        }

        public static Dictionary<int, string> ParseMapIntString(string s)
        {
            var res = new Dictionary<int, string>();
            if (string.IsNullOrWhiteSpace(s)) return res;
            foreach (var pair in s.Split('|'))
            {
                var p = pair.Trim();
                if (p == "") continue;
                var kv = p.Split(new[] { ';' }, 2);
                if (kv.Length != 2) kv = p.Split(new[] { ':' }, 2);
                if (kv.Length != 2) continue;
                res[ToInt(kv[0])] = kv[1].Trim();
            }
            return res;
        }

        public static int[] ParseSliceInt(string s)
        {
            var res = new List<int>();
            if (string.IsNullOrWhiteSpace(s)) return res.ToArray();
            foreach (var e in s.Split(';'))
            {
                var x = e.Trim();
                if (x == "") continue;
                res.Add(ToInt(x));
            }
            return res.ToArray();
        }

        public static string[] ParseSliceString(string s)
        {
            var res = new List<string>();
            if (string.IsNullOrWhiteSpace(s)) return res.ToArray();
            foreach (var e in s.Split(';')) res.Add(e.Trim());
            return res.ToArray();
        }

        public static Vector3 ParseVector3(string s)
        {
            var v = new Vector3();
            if (string.IsNullOrWhiteSpace(s)) return v;
            var sep = s.IndexOf(';') >= 0 ? ';' : ',';
            var parts = s.Split(sep);
            if (parts.Length > 0) v.X = ToFloat(parts[0]);
            if (parts.Length > 1) v.Y = ToFloat(parts[1]);
            if (parts.Length > 2) v.Z = ToFloat(parts[2]);
            return v;
        }
    }
}
