// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseDemoRow 表 "demo_cs" 的一行（强类型）。
	public class BaseDemoRow
	{
		public int IAmInt; // 数字
		public int IAmInt32; // 数字
		public long IAmInt64; // 数字
		public float IAmFloat64; // 小数
		public float IAmFloat32; // 小数
		public string IAmStr; // 字符串
		public Dictionary<int, int> IAmMapIntInt1; // 复合kv
		public Dictionary<int, string> IAmMapIntInt2; // 复合kv
		public int[] IAmSliceInt; // 数组
		public string[] IAmSliceString; // 数组
		public Vector3 IAmVector3; // xzy
	}

	// BaseDemoTable 表 "demo_cs" 的只读容器（按主键索引）。
	public class BaseDemoTable
	{
		private List<BaseDemoRow> rows = new List<BaseDemoRow>();
		private Dictionary<int, BaseDemoRow> index = new Dictionary<int, BaseDemoRow>();

		public BaseDemoRow Get(int id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseDemoRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseDemoRow>();
			index = new Dictionary<int, BaseDemoRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseDemoRow();
				row.IAmInt = TableParsers.ToInt(TableParsers.Cell(rec, 0));
				row.IAmInt32 = TableParsers.ToInt(TableParsers.Cell(rec, 1));
				row.IAmInt64 = TableParsers.ToLong(TableParsers.Cell(rec, 2));
				row.IAmFloat64 = TableParsers.ToFloat(TableParsers.Cell(rec, 3));
				row.IAmFloat32 = TableParsers.ToFloat(TableParsers.Cell(rec, 4));
				row.IAmStr = TableParsers.Cell(rec, 5);
				row.IAmMapIntInt1 = TableParsers.ParseMapIntInt(TableParsers.Cell(rec, 6));
				row.IAmMapIntInt2 = TableParsers.ParseMapIntString(TableParsers.Cell(rec, 7));
				row.IAmSliceInt = TableParsers.ParseSliceInt(TableParsers.Cell(rec, 8));
				row.IAmSliceString = TableParsers.ParseSliceString(TableParsers.Cell(rec, 9));
				row.IAmVector3 = TableParsers.ParseVector3(TableParsers.Cell(rec, 10));
				rows.Add(row);
				index[row.IAmInt] = row;
			}
		}
	}
}
