// Code generated by core. DO NOT EDIT (base registry, regenerated each run).
import { BaseDemoTable } from "./base_demo";

// BaseTables 持有全部 base 表实例。
export class BaseTables {
	demo = new BaseDemoTable();

	// LoadAll 从 tsvOf(name) 取得各表 tsv 文本并加载（name 不含扩展名）。
	loadAll(tsvOf: (name: string) => string): void {
		this.demo.load(tsvOf("demo"));
	}
}
