// Code generated by core. DO NOT EDIT (base runtime, regenerated each run).
export interface Vector3 { x: number; y: number; z: number; }

export function cell(rec: string[], i: number): string {
	if (i < 0 || i >= rec.length) return "";
	return rec[i];
}

function toInt(s: string): number {
	s = (s || "").trim();
	if (s === "") return 0;
	const v = parseInt(s, 10);
	return isNaN(v) ? 0 : v;
}

function toFloat(s: string): number {
	s = (s || "").trim();
	if (s === "") return 0;
	const v = parseFloat(s);
	return isNaN(v) ? 0 : v;
}

export function parseMapIntInt(s: string): Map<number, number> {
	const out = new Map<number, number>();
	s = (s || "").trim();
	if (s === "") return out;
	for (const pair of s.split("|")) {
		const p = pair.trim();
		if (p === "") continue;
		let kv = p.split(";");
		if (kv.length !== 2) kv = p.split(":");
		if (kv.length !== 2) continue;
		out.set(toInt(kv[0]), toInt(kv[1]));
	}
	return out;
}

export function parseMapIntString(s: string): Map<number, string> {
	const out = new Map<number, string>();
	s = (s || "").trim();
	if (s === "") return out;
	for (const pair of s.split("|")) {
		const p = pair.trim();
		if (p === "") continue;
		let kv = p.split(";");
		if (kv.length !== 2) kv = p.split(":");
		if (kv.length !== 2) continue;
		out.set(toInt(kv[0]), kv[1].trim());
	}
	return out;
}

export function parseSliceInt(s: string): number[] {
	const out: number[] = [];
	s = (s || "").trim();
	if (s === "") return out;
	for (const e of s.split(";")) {
		const x = e.trim();
		if (x === "") continue;
		out.push(toInt(x));
	}
	return out;
}

export function parseSliceString(s: string): string[] {
	const out: string[] = [];
	s = (s || "").trim();
	if (s === "") return out;
	for (const e of s.split(";")) out.push(e.trim());
	return out;
}

export function parseVector3(s: string): Vector3 {
	const v: Vector3 = { x: 0, y: 0, z: 0 };
	s = (s || "").trim();
	if (s === "") return v;
	const sep = s.indexOf(";") >= 0 ? ";" : ",";
	const parts = s.split(sep);
	const nums = [0, 0, 0];
	let n = 0;
	for (const p of parts) {
		if (n > 2) break;
		nums[n] = toFloat(p);
		n++;
	}
	v.x = nums[0]; v.y = nums[1]; v.z = nums[2];
	return v;
}
