// Code generated by core. DO NOT EDIT (base, regenerated each run).
import { parseMapIntInt, parseMapIntString, parseSliceInt, parseSliceString, parseVector3, Vector3, cell } from "./base_table";

// BaseDemoRow 表 "demo_cs" 的一行（强类型）。
export interface BaseDemoRow {
	iAmInt: number; // 数字
	iAmInt32: number; // 数字
	iAmInt64: number; // 数字
	iAmFloat64: number; // 小数
	iAmFloat32: number; // 小数
	iAmStr: string; // 字符串
	iAmMapIntInt1: Map<number, number>; // 复合kv
	iAmMapIntInt2: Map<number, string>; // 复合kv
	iAmSliceInt: number[]; // 数组
	iAmSliceString: string[]; // 数组
	iAmVector3: Vector3; // xzy
}

// BaseDemoTable 表 "demo_cs" 的只读容器（按主键索引）。
export class BaseDemoTable {
	private rows: BaseDemoRow[] = [];
	private index = new Map<number, BaseDemoRow>();

	get(id: number): BaseDemoRow | undefined { return this.index.get(id); }
	get length(): number { return this.rows.length; }
	all(): BaseDemoRow[] { return this.rows; }

	// Load 从 tsv 文本加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
	load(text: string): void {
		const lines = text.split(/\r?\n/).filter(l => l.length > 0);
		if (lines.length < 1) return;
		this.rows = [];
		this.index = new Map<number, BaseDemoRow>();
		for (let li = 1; li < lines.length; li++) {
			const rec = lines[li].split("\t");
			const row: BaseDemoRow = {
				iAmInt: parseInt(cell(rec, 0), 10) || 0,
				iAmInt32: parseInt(cell(rec, 1), 10) || 0,
				iAmInt64: parseInt(cell(rec, 2), 10) || 0,
				iAmFloat64: parseFloat(cell(rec, 3)) || 0,
				iAmFloat32: parseFloat(cell(rec, 4)) || 0,
				iAmStr: cell(rec, 5),
				iAmMapIntInt1: parseMapIntInt(cell(rec, 6)),
				iAmMapIntInt2: parseMapIntString(cell(rec, 7)),
				iAmSliceInt: parseSliceInt(cell(rec, 8)),
				iAmSliceString: parseSliceString(cell(rec, 9)),
				iAmVector3: parseVector3(cell(rec, 10)),
			};
			this.rows.push(row);
			this.index.set(row.iAmInt, row);
		}
	}
}
