// Code generated by core. DO NOT EDIT (上层 registry，每次运行重新生成)。
package table

import (
	"os"
	"path/filepath"
)

// Tables 持有全部业务表实例（按名索引）。
type Tables struct {
	Demo *DemoTable
}

// Default 全局配置表单例。首次调用 NewTables 时被赋值；引擎加载该实例后，
// 业务任意处可直接 table.Default.<表名>.Get(id) 读取，无需再 NewTables。
var Default *Tables

// NewTables 创建全部业务表实例，并设为全局单例 Default。
func NewTables() *Tables {
	t := &Tables{
		Demo: NewDemoTable(),
	}
	Default = t
	return t
}

var OnLoadedOne func(name string, count int)

type tsvTable interface {
	Load(content string) error
	Clear()
	Len() int
}

// loadTable 单表加载：读取 <dir>/<name>.tsv 并 Load(content)；文件缺失则清空该表；
// 完成后触发 OnLoadedOne 钩子（由引擎接线到 table.LoadedOne 事件）。
func loadTable(tbl tsvTable, dir, name string) error {
	p := filepath.Join(dir, name+".tsv")
	if _, err := os.Stat(p); err == nil {
		b, rerr := os.ReadFile(p)
		if rerr != nil {
			return rerr
		}
		if err := tbl.Load(string(b)); err != nil {
			return err
		}
		if OnLoadedOne != nil {
			OnLoadedOne(name, tbl.Len())
		}
		return nil
	}
	// file 缺失：清空数据（不报错，便于后续覆盖式热更）。
	tbl.Clear()
	if OnLoadedOne != nil {
		OnLoadedOne(name, 0)
	}
	return nil
}

// LoadAll 从 dir 加载全部业务表（每张表读 <dir>/<逻辑名>.tsv，如 demo.tsv）。
// 每加载完一张表触发 OnLoadedOne 钩子（由引擎接线到 table.LoadedOne 事件）。
func (t *Tables) LoadAll(dir string) error {
	if err := loadTable(t.Demo, dir, "demo"); err != nil {
		return err
	}
	return nil
}
