// Code generated by core. EDITABLE (上层，首次生成后不再覆盖)。
// 业务可在此安全追加逻辑、覆写下方三个加载钩子。
import { BaseDemoTable, BaseDemoRow } from "./base/base_demo";

export class DemoTable extends BaseDemoTable {
	onBeforeLoad(): void {}
	onLoadRow(row: BaseDemoRow): void {}
	onAfterLoad(): void {}
	load(text: string): void {
		this.onBeforeLoad();
		super.load(text);
		for (const row of this.all()) this.onLoadRow(row);
		this.onAfterLoad();
	}
}
