// Code generated by core. DO NOT EDIT (上层 registry，每次运行重新生成)。
import { DemoTable } from "./demo";

// Tables 持有全部业务表实例。
export class Tables {
	demo = new DemoTable();

	// LoadAll 从 tsvOf(name) 取得各表 tsv 文本并加载（触发各表钩子）。
	loadAll(tsvOf: (name: string) => string): void {
		this.demo.load(tsvOf("demo"));
	}
}

// Default 全局配置表单例（eager）。引擎加载后即为已加载实例，业务直接 Default.<表名>.get(id)。
export const Default = new Tables();
