// Code generated by core. EDITABLE (上层，首次生成后不再覆盖)。
// 业务可在此安全追加逻辑、覆写下方三个加载钩子。
package table

import "table/base"

// 是 BaseDemoTable 的业务扩展层（嵌入 base，自动获得 Row/Table/Get/Load 能力）。
type DemoTable struct {
	*base.BaseDemoTable
}

// 构建业务表（底层为 base 表）。
func NewDemoTable() *DemoTable {
	return &DemoTable{BaseDemoTable: base.NewBaseDemoTable()}
}

// 加载前钩子（按需覆写）。
func (t *DemoTable) OnBeforeLoad() {}

// 逐行加载钩子（按需覆写）；row 为该行强类型视图。
func (t *DemoTable) OnLoadRow(row *base.BaseDemoRow) {}

// 加载后钩子（按需覆写）。
func (t *DemoTable) OnAfterLoad() {}

// 从 tsv 文本加载，并在加载前/中/后触发钩子。
func (t *DemoTable) Load(content string) error {
	t.OnBeforeLoad()
	if err := t.BaseDemoTable.Load(content); err != nil {
		return err
	}
	for _, row := range t.Rows() {
		t.OnLoadRow(row)
	}
	t.OnAfterLoad()
	return nil
}
