// Code generated by core. DO NOT EDIT (base registry, regenerated each run).
package base

import (
	"os"
	"path/filepath"
)

// BaseTables 持有全部 base 表实例（按名索引），便于一次性加载。
type BaseTables struct {
	Demo *BaseDemoTable
}

// NewBaseTables 创建全部 base 表实例（空数据）。
func NewBaseTables() *BaseTables {
	return &BaseTables{
		Demo: NewBaseDemoTable(),
	}
}

// baseTable 所有 base 表共有的加载接口。
type baseTable interface {
	Load(content string) error
	Len() int
}

// LoadAllBase 从 dir 加载全部 base 表（dir/<name>.tsv）。
func (t *BaseTables) LoadAllBase(dir string) error {
	for _, p := range []struct {
		tbl  baseTable
		name string
	}{
		{t.Demo, "demo"},
	} {
		b, err := os.ReadFile(filepath.Join(dir, p.name+".tsv"))
		if err != nil {
			return err
		}
		if err := p.tbl.Load(string(b)); err != nil {
			return err
		}
	}
	return nil
}
