// Code generated by core. DO NOT EDIT (base, regenerated each run).
package base

import (
	"encoding/csv"
	"fmt"
	"strings"
)

// BaseDemoRow 表 "demo" 的一行（强类型）。
type BaseDemoRow struct {
	IAmInt int // 数字
	IAmInt32 int32 // 数字
	IAmInt64 int64 // 数字
	IAmFloat64 float64 // 小数
	IAmFloat32 float32 // 小数
	IAmStr string // 字符串
	IAmMapIntInt1 map[int]int // 复合kv
	IAmMapIntInt2 map[int]string // 复合kv
	IAmSliceInt []int // 数组
	IAmSliceString []string // 数组
	IAmVector3 Vector3 // xzy
}

// BaseDemoTable 表 "demo" 的只读容器（按主键索引）。
type BaseDemoTable struct {
	rows  []*BaseDemoRow
	index map[int]*BaseDemoRow
}

// NewBaseDemoTable 创建空表。
func NewBaseDemoTable() *BaseDemoTable {
	return &BaseDemoTable{index: make(map[int]*BaseDemoRow)}
}

// Get 按主键取行（不存在返回 nil）。
func (t *BaseDemoTable) Get(id int) *BaseDemoRow {
	return t.index[id]
}

// Len 当前行数。
func (t *BaseDemoTable) Len() int { return len(t.rows) }

// Rows 返回全部行（只读视图）。
func (t *BaseDemoTable) Rows() []*BaseDemoRow { return t.rows }

// Load 从 tsv 文本加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
// redis 等内存源拿到原始 tsv 文本直接传 content；file 源由 registry 读取后传入。
func (t *BaseDemoTable) Load(content string) error {
	r := csv.NewReader(strings.NewReader(content))
	r.Comma = '\t'
	r.FieldsPerRecord = -1
	r.TrimLeadingSpace = true
	recs, err := r.ReadAll()
	if err != nil {
		return fmt.Errorf("BaseDemoTable: 解析 tsv 失败: %w", err)
	}
	if len(recs) < 1 {
		return fmt.Errorf("BaseDemoTable: tsv 无数据")
	}
	// 整体替换
	t.rows = nil
	t.index = make(map[int]*BaseDemoRow)
	for _, rec := range recs[1:] {
		row := &BaseDemoRow{}
		row.IAmInt = parseInt(cell(rec, 0))
		row.IAmInt32 = parseInt32(cell(rec, 1))
		row.IAmInt64 = parseInt64(cell(rec, 2))
		row.IAmFloat64 = parseFloat64(cell(rec, 3))
		row.IAmFloat32 = parseFloat32(cell(rec, 4))
		row.IAmStr = cell(rec, 5)
		row.IAmMapIntInt1 = parseMapIntInt(cell(rec, 6))
		row.IAmMapIntInt2 = parseMapIntString(cell(rec, 7))
		row.IAmSliceInt = parseSliceInt(cell(rec, 8))
		row.IAmSliceString = parseSliceString(cell(rec, 9))
		row.IAmVector3 = parseVector3(cell(rec, 10))
		t.rows = append(t.rows, row)
		t.index[row.IAmInt] = row
	}
	return nil
}

// Clear 清空全部数据。
func (t *BaseDemoTable) Clear() {
	t.rows = nil
	t.index = make(map[int]*BaseDemoRow)
}
