// Code generated by core. DO NOT EDIT (base runtime, regenerated each run).
package base

import (
	"strconv"
	"strings"
)

// 三维向量（策划用 ';' 或 ',' 分隔的三个浮点数）。
type Vector3 struct {
	X float32
	Y float32
	Z float32
}

// 安全取第 i 个单元格（越界返回空串）。
func cell(rec []string, i int) string {
	if i < 0 || i >= len(rec) {
		return ""
	}
	return rec[i]
}

func parseInt(s string) int {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	v, err := strconv.Atoi(s)
	if err != nil {
		return 0
	}
	return v
}

func parseInt32(s string) int32 {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	v, err := strconv.ParseInt(s, 10, 32)
	if err != nil {
		return 0
	}
	return int32(v)
}

func parseInt64(s string) int64 {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	v, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return 0
	}
	return v
}

func parseFloat32(s string) float32 {
	return float32(parseFloat64(s))
}

func parseFloat64(s string) float64 {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 0
	}
	return v
}

// 解析 "k;v|k;v" 或 "k:v|k:v"（';' 与 ':' 均可作 kv 分隔）。
func parseMapIntInt(s string) map[int]int {
	out := map[int]int{}
	s = strings.TrimSpace(s)
	if s == "" {
		return out
	}
	for _, pair := range strings.Split(s, "|") {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}
		kv := strings.SplitN(pair, ";", 2)
		if len(kv) != 2 {
			kv = strings.SplitN(pair, ":", 2)
		}
		if len(kv) != 2 {
			continue
		}
		k := parseInt(kv[0])
		v := parseInt(kv[1])
		out[k] = v
	}
	return out
}

// 解析 "k;v|k;v"（value 为原样字符串）。
func parseMapIntString(s string) map[int]string {
	out := map[int]string{}
	s = strings.TrimSpace(s)
	if s == "" {
		return out
	}
	for _, pair := range strings.Split(s, "|") {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}
		kv := strings.SplitN(pair, ";", 2)
		if len(kv) != 2 {
			kv = strings.SplitN(pair, ":", 2)
		}
		if len(kv) != 2 {
			continue
		}
		out[parseInt(kv[0])] = strings.TrimSpace(kv[1])
	}
	return out
}

// 解析 "a;b;c"（';' 分隔）。
func parseSliceInt(s string) []int {
	out := []int{}
	s = strings.TrimSpace(s)
	if s == "" {
		return out
	}
	for _, e := range strings.Split(s, ";") {
		e = strings.TrimSpace(e)
		if e == "" {
			continue
		}
		out = append(out, parseInt(e))
	}
	return out
}

// 解析 "a;b;c"（';' 分隔，保留原样）。
func parseSliceString(s string) []string {
	out := []string{}
	s = strings.TrimSpace(s)
	if s == "" {
		return out
	}
	for _, e := range strings.Split(s, ";") {
		out = append(out, strings.TrimSpace(e))
	}
	return out
}

// 解析 "x;y;z" 或 "x,y,z"，取前三个浮点。
func parseVector3(s string) Vector3 {
	var v Vector3
	s = strings.TrimSpace(s)
	if s == "" {
		return v
	}
	sep := ";"
	if !strings.Contains(s, ";") && strings.Contains(s, ",") {
		sep = ","
	}
	parts := strings.Split(s, sep)
	n := 0
	for _, p := range parts {
		f := parseFloat64(p)
		switch n {
		case 0:
			v.X = float32(f)
		case 1:
			v.Y = float32(f)
		case 2:
			v.Z = float32(f)
		default:
			return v
		}
		n++
	}
	return v
}
