// Code generated by core. DO NOT EDIT (base registry, regenerated each run).
package base

import (
	"os"
	"path/filepath"
)

// 持有全部 base 表实例（按名索引），便于一次性加载。
type BaseTables struct {
	Demo *BaseDemoTable
}

// 创建全部 base 表实例（空数据）。
func NewBaseTables() *BaseTables {
	return &BaseTables{
		Demo: NewBaseDemoTable(),
	}
}

// 从 dir 加载全部 base 表（dir/<name>.tsv）。
func (t *BaseTables) LoadAllBase(dir string) error {
	b, err := os.ReadFile(filepath.Join(dir, "demo.tsv"))
	if err != nil {
		return err
	}
	if err := t.Demo.Load(string(b)); err != nil {
		return err
	}
	return nil
}
