// Code generated by core. EDITABLE (上层，首次生成后不再覆盖)。
// 业务可在此安全追加逻辑、覆写下方三个加载钩子。
using System;

namespace Table
{
    public class DemoTable : BaseDemoTable
    {
        public virtual void OnBeforeLoad() { }
        public virtual void OnLoadRow(BaseDemoRow row) { }
        public virtual void OnAfterLoad() { }

        // LoadWithHooks 加载 tsv 并在加载前/中/后触发钩子。
        public void LoadWithHooks(string path)
        {
            OnBeforeLoad();
            base.Load(path);
            foreach (var row in All()) OnLoadRow(row);
            OnAfterLoad();
        }
    }
}
