// Code generated by core. DO NOT EDIT (上层 registry，每次运行重新生成)。
using System.IO;

namespace Table
{
	public class Tables
	{
		// Default 全局配置表单例。引擎加载后即为已加载实例，业务直接 Tables.Default.<表名>.Get(id)。
		public static Tables Default = new Tables();
		public DemoTable Demo = new DemoTable();

		// LoadAll 从 dir 加载全部业务表（dir/<name>.tsv），并触发各表钩子。
		public void LoadAll(string dir)
		{
			Demo.LoadWithHooks(Path.Combine(dir, "Demo.tsv"));
		}
	}
}
